<?php

namespace App\Libraries;

use GuzzleHttp\Client;
use Illuminate\Support\Facades\DB;

/**
 * Anteraja API - Laravel Library
 * Based on Anteraja Official Documentation (https://developer.anteraja.id/#anteraja-api-documentation-v2-0-7)
 */

class Anteraja
{
    public static function check_tariff($origin, $destination, $weight = 1)
    {
        // $endpoint = env('ANTERAJA_BASE_PATH') . '/serviceRates';
        $endpoint = env('ANTERAJA_BASE_PATH') . '/calculate/domestic-cost';

        $access_key_id = env('ANTERAJA_ACCESS_KEY_ID');
        $secret_access_key = env('ANTERAJA_SECRET_ACCESS_KEY');

        // if (!$access_key_id || !$secret_access_key) {
        if (!$access_key_id) {
            if (env('APP_DEBUG')) {
                return 'Auth credentials for Anteraja is not set';
            } else {
                return false;
            }
        }

        /**
         * origin & destination used area code that generated by Anteraja
         * 
         * Parcel weight in gram(s). Minimum is 1,000. Maximum is 50,000.
         */

        // so need to convert weight from kg to gram
        $weight = $weight * 1000;
        // set minimum
        if ($weight < 1000) {
            $weight = 1000;
        }
        // dd($origin, $destination);

        if (empty($origin) || empty($destination)) {
            return 'Origin and destination must be set.';
        }

        try {
            $courier = "jne:sicepat:jnt:ninja:anteraja:lion";

            $client = new Client();
            // $headers = [
            //     'access-key-id' => $access_key_id,
            //     'secret-access-key' => $secret_access_key,
            //     'Content-Type' => 'application/json',
            // ];
            // $result = $client->request('POST', $endpoint, [
            //     'headers' => $headers,
            //     'json' => [
            //         'origin' => $origin,
            //         'destination' => $destination,
            //         'weight' => $weight
            //     ]
            // ]);
            $headers = [
                // 'secret-access-key' => $secret_access_key,
                'key' => $access_key_id,
                'accept' => 'application/json',
                'content-type' => 'application/x-www-form-urlencoded',
            ];
            $json = [
                'origin' => $origin,
                'destination' => $destination,
                'weight' => $weight,
                'courier' => $courier,
                'price' => 'lowest'
            ];
            // dd($json);
            $result = $client->request('POST', $endpoint, [
                'headers' => $headers,
                'form_params' => $json,
            ]);
            $response = json_decode($result->getBody()->getContents());
            // dd($response->data);

            return [
                'status' => true,
                // 'data' => $response->content->services
                'data' => $response->data
            ];

            // * Success Response Sample
            // array:2 [▼
            //     "status" => true
            //     "data" => array:3 [▼
            //         0 => {#761 ▼
            //             +"product_code": "REG"
            //             +"product_name": "Regular"
            //             +"etd": "1-2 Day"
            //             +"rates": 10000
            //         }
            //         1 => {#751 ▼
            //             +"product_code": "ND"
            //             +"product_name": "Next Day"
            //             +"etd": "1 Day"
            //             +"rates": 13000
            //         }
            //         2 => {#758 ▼
            //             +"product_code": "SD"
            //             +"product_name": "Same Day"
            //             +"etd": "0 Day"
            //             +"rates": 20000
            //         }
            //     ]
            // ]
            // "meta": {#1014 ▶
            //     +"message": "Success Calculate Domestic Shipping cost"
            //     +"code": 200
            //     +"status": "success"
            // }
            // +"data": array:2 [▶
            //     0 => {#1029 ▶
            //     +"name": "Jalur Nugraha Ekakurir (JNE)"
            //     +"code": "jne"
            //     +"service": "REG"
            //     +"description": "Layanan Reguler"
            //     +"cost": 70000
            //     +"etd": "5 day"
            //     }
            //     1 => {#1020 ▶
            //     +"name": "Jalur Nugraha Ekakurir (JNE)"
            //     +"code": "jne"
            //     +"service": "JTR"
            //     +"description": "JNE Trucking"
            //     +"cost": 180000
            //     +"etd": "10 day"
            //     }
            // ]
        } catch (\GuzzleHttp\Exception\ClientException $e) {
            $response = $e->getResponse();
            dd($response, $response->getBody()->getContents(), $e);
            $responseBodyAsString = json_decode($response->getBody()->getContents());
            # ERROR
            return [
                'status' => false,
                'info' => $responseBodyAsString->info
            ];

            // * Error Response Sample
            // array:2 [▼
            //     "status" => false
            //     "info" => "District not found : 31.72.55"
            // ]
        }

        # INTERNAL ERROR
        return [
            'status' => false,
            'info' => 'Internal Server Error in Anteraja Library'
        ];
    }

    public static function create_order($invoice_no, $service_type, $total_weight_grams, $shipper, $receiver, $items, $use_insurance, $declared_value, $expect_time, $data)
    {
        // $endpoint = env('ANTERAJA_BASE_PATH') . '/order';
        $endpoint = env('RAJAONGKIR_BASE_PATH') . '/order/api/v1/orders/store';
        $endpoint_pickup = env('RAJAONGKIR_BASE_PATH') . '/order/api/v1/pickup/request';

        $access_key_id = env('RAJAONGKIR_ACCESS_KEY_ID');
        $secret_access_key = env('ANTERAJA_SECRET_ACCESS_KEY');

        // if (!$access_key_id || !$secret_access_key) {
        if (!$access_key_id) {
            return [
                'status' => false,
                'info' => 'Auth credentials for Anteraja is not set'
            ];
        }

        // generate booking_id
        $prefix = env('ANTERAJA_PREFIX_ORDER');
        $booking_id = $prefix . '-' . $invoice_no;

        // if (!in_array($service_type, ['REG', 'ND', 'SD'])) {
        //     switch ($service_type) {
        //         case 'Regular':
        //             $service_type = 'REG';
        //             break;
        //         case 'Anteraja Regular':
        //             $service_type = 'REG';
        //             break;

        //         case 'Next Day':
        //             $service_type = 'ND';
        //             break;
        //         case 'Anteraja Next Day':
        //             $service_type = 'ND';
        //             break;

        //         case 'Same Day':
        //             $service_type = 'SD';
        //             break;
        //         case 'Anteraja Same Day':
        //             $service_type = 'SD';
        //             break;

        //         default:
        //             # ERROR
        //             return [
        //                 'status' => false,
        //                 'info' => 'Invalid Service Type'
        //             ];
        //             break;
        //     }
        // }
        if (empty($service_type)) {
            # ERROR
            return [
                'status' => false,
                'info' => 'Invalid Service Type'
            ];
        }

        if ($total_weight_grams < 1000) {
            $total_weight_grams = 1000;
        } elseif ($total_weight_grams > 50000) {
            # ERROR
            return [
                'status' => false,
                'info' => 'Total Weight exceeded'
            ];
        }

        try {
            $client = new Client();
            // $headers = [
            //     'access-key-id' => $access_key_id,
            //     'secret-access-key' => $secret_access_key,
            //     'Content-Type' => 'application/json',
            // ];
            // $json = [
            //     'booking_id' => $booking_id,
            //     'invoice_no' => $invoice_no,
            //     'service_code' => $service_type,
            //     'parcel_total_weight' => $total_weight_grams,
            //     'shipper' => $shipper,
            //     'receiver' => $receiver,
            //     'items' => $items,
            //     'use_insurance' => $use_insurance,
            //     'declared_value' => $declared_value,
            //     'expect_time' => $expect_time
            // ];
            // $result = $client->request('POST', $endpoint, [
            //     'headers' => $headers,
            //     'json' => $json
            // ]);
            // $response = json_decode($result->getBody()->getContents());
            $headers = [
                'x-api-key' => $access_key_id,
            ];
            
            $payment_method = implode(' ', explode('_', $data->payment_method));
            $shipping_type = explode(' ', $data->shipper_service_type);
            $shipping = strtoupper($shipping_type[0]);
            $brand_name = $data->product_item_name . ' ' . $data->product_item_variant_name;
            
            $json = [
                "order_date" => $data->paid_at,                        
                "brand_name" => $brand_name,                                    
                "shipper_name" => $data->shipper_name,                    
                "shipper_phone" => $shipper->phone,                           
                "shipper_destination_id" => 1,                            
                "shipper_address" => "Jl. Nasional 12, RT.6/RW.2, Grogol Selatan., Kec. Kebayoran Lama, Kota Jakarta Selatan",                  
                "shipper_email" => $shipper->email,                          
                "receiver_name" => $receiver->name,                                 
                "receiver_phone" => $receiver->phone,                          
                "receiver_destination_id" => 39947,                           
                "receiver_address" => $receiver->address,     
                "shipping" => $shipping,                                          
                "shipping_type" => $shipping_type[1],                                      
                "payment_method" => $payment_method,                                    
                "shipping_cost" => $data->price_shipping,
                "shipping_cashback" => 0,
                "service_fee" => 0,
                "additional_cost" => 0,
                "grand_total" => $data->price_total,
                "cod_value" => 0,
                "insurance_value" => 0,
                "order_details" => $items
            ];
            // dd($json, $headers, $endpoint);
            $result = $client->request('POST', $endpoint, [
                'headers' => $headers,
                'json' => $json,
                'debug' => true
            ]);
            $response = json_decode($result->getBody()->getContents());

            // logging
            DB::table('courier_anteraja_logs')->insert(
                [
                    'method' => 'POST',
                    'endpoint' => $endpoint,
                    'headers' => json_encode($headers),
                    'params_type' => 'json',
                    'params' => json_encode($json),
                    'response' => json_encode($response),
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s')
                ]
            );

            $headers_pickup = [
                'x-api-key' => $access_key_id,
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
            ];

            $pickupDateTime = new \DateTime('now', new \DateTimeZone('Asia/Jakarta'));
            $pickupDateTime->modify('+2 hours');

            $json_pickup = [
                "pickup_date" => $pickupDateTime->format('Y-m-d'),
                "pickup_time" => $pickupDateTime->format('H:i'),
                "pickup_vehicle" => "Motor", // Motor/Mobil/Truck
                "orders" => [
                    [
                        "order_no" => $response->data->order_no
                    ]
                ]
            ];
            $result_pickup = $client->request('POST', $endpoint_pickup, [
                'headers' => $headers_pickup,
                'json' => $json_pickup,
                'debug' => true
            ]);
            $response_pickup = json_decode($result_pickup->getBody()->getContents());

            return [
                'status' => true,
                'data' => $response_pickup->data
            ];
        } catch (\GuzzleHttp\Exception\ClientException $e) {
            $response = $e->getResponse();
            // dd('asd',$response, $response->getBody()->getContents(), $e);
            $responseBodyAsString = json_decode($response->getBody()->getContents());
            // dd($responseBodyAsString->meta->message);
            # ERROR
            return [
                'status' => false,
                'info' => $responseBodyAsString->meta->message
            ];

            // * Error Response Sample
            // array:2 [▼
            //     "status" => false
            //     "info" => "District not found : 31.72.55"
            // ]
        }

        # INTERNAL ERROR
        return [
            'status' => false,
            'info' => 'Internal Server Error in Anteraja Library'
        ];
    }

    public static function generate_awb($shipper, $customer, $product, $origin, $destination, $options)
    {
        
    }
}
